#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate a CRC-16/0x1021 XOR network with greedy common-pair sharing.
# Run from any directory; output is deterministic. This is a size heuristic,
# not a proof of optimality. Ties prefer shallower intermediate expressions.
require 'set'

# Symbolic GF(2) propagation: each set describes one XOR of input bits.
state = Array.new(16) { |i| Set[i] }
127.downto(0) do |bit|
  feedback = state[15] ^ Set[16 + bit]
  state = [Set.new] + state.first(15)
  [0, 5, 12].each { |tap| state[tap] ^= feedback }
end

names = Array.new(16) { |i| "crc[#{i}:#{i + 1}]" }
names.concat(Array.new(128) { |i| "data[#{i}:#{i + 1}]" })
depths = Array.new(names.length, 0)
lines = [
  '// Generated by utils/generate_crc128.rb; do not edit by hand.',
  '// CRC-16/0x1021, data[127] first; explicit shared XOR expressions.',
  '// Greedy area heuristic, with depth as a tie-breaker; no registers.',
  'pub fn crc16_block(crc: u16, data: uN[128]) -> u16 {'
]
loop do
  counts = Hash.new(0)
  state.each { |terms| terms.to_a.sort.combination(2) { |pair| counts[pair] += 1 } }
  break if counts.empty?

  pair = counts.keys.min_by { |a, b| [-counts[[a, b]], [depths[a], depths[b]].max, a, b] }
  break if counts[pair] < 2

  a, b = pair
  index = names.length
  name = "x#{index - 144}"
  lines << "  let #{name} = #{names[a]} ^ #{names[b]};"
  names << name
  depths << 1 + [depths[a], depths[b]].max
  state.each do |terms|
    next unless terms.include?(a) && terms.include?(b)

    terms.delete(a)
    terms.delete(b)
    terms.add(index)
  end
end

# Combine remaining terms in balanced trees, taking existing depth into account.
state.each_with_index do |terms, bit|
  pending = terms.map { |i| [depths[i], names[i]] }.sort
  while pending.length > 1
    da, a = pending.shift
    db, b = pending.shift
    pending << [[da, db].max + 1, "(#{a} ^ #{b})"]
    pending.sort!
  end
  lines << "  let out#{bit} = #{pending[0][1]};"
end
lines << '  ' + 15.downto(0).map { |i| "out#{i}" }.join(' ++ ')
lines << '}'
output = File.expand_path('../crc/crc_optimized.x', __dir__)
File.write(output, lines.join("\n") + "\n")
